apiVersion: v1
kind: ConfigMap
metadata:
  name: execution-service
  namespace: tech-challenge
data:
  NODE_ENV: production
  PORT: "3002"
  RABBITMQ_QUEUE: execution_queue
  DD_SERVICE: execution-service
  DD_ENV: production
  DD_SITE: datadoghq.com
  DD_AGENT_HOST: datadog-agent.datadog.svc.cluster.local
