apiVersion: v1
kind: Service
metadata:
  name: execution-service
  namespace: tech-challenge
  labels:
    app: execution-service
    app.kubernetes.io/name: execution-service
    app.kubernetes.io/part-of: tech-challenge
spec:
  type: ClusterIP
  selector:
    app: execution-service
  ports:
    - name: http
      port: 3002
      targetPort: http
      protocol: TCP
