apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service
  namespace: tech-challenge
data:
  NODE_ENV: production
  PORT: "3003"
  JWT_TTL_SECONDS: "86400"
  CUSTOMER_LOOKUP_URL: http://work-order-service:3000/customers/lookup
  DD_SERVICE: auth-service
  DD_ENV: production
  DD_SITE: datadoghq.com
  DD_AGENT_HOST: datadog-agent.datadog.svc.cluster.local
