apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: tech-challenge
  labels:
    app: auth-service
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: tech-challenge
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 3003
      targetPort: http
      protocol: TCP
